name: Upstream Sync

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * 0" # 每周执行
  workflow_dispatch:

env:
  UPSTREAM_REPO: imsyy/vitepress-theme-curve # 定义上游仓库地址

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3

      # 添加上游仓库作为远程仓库
      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/${{ env.UPSTREAM_REPO }}.git

      # 获取上游更改
      - name: Fetch upstream changes
        run: git fetch upstream

      # 合并上游仓库的 master 分支到目标 main 分支
      - name: Merge upstream changes
        run: |
          git checkout main
          git merge upstream/master -X ours --no-edit || {
            echo "[Warning] 合并时发生冲突，保留本地版本。"
            exit 0  # 继续执行后续步骤
          }

      # 推送更改到目标仓库
      - name: Push changes
        run: git push origin main

      # 同步检查
      - name: Sync check
        if: failure()
        run: |
          echo "[Error] 由于上游仓库的 workflow 文件变更，导致 GitHub 自动暂停了本次自动更新，你需要手动 Sync Fork 一次，详细教程请查看项目README.md"
          echo "[Error] Due to a change in the workflow file of the upstream repository, GitHub has automatically suspended the scheduled automatic update. You need to manually sync your fork. Please refer to the project README.md for instructions."
          exit 1
